### PR TITLE
Keybindings customization

### PR DESCRIPTION
**Pull request by fsioni**
Hello again :)
I opened this new PR because I didn't manage to discard the old and obsolete commit.

- It now uses the new Input System
- New controls settings menu
- You can change any keybind sets in Input Action
- There is a UI prefab, you just need to select the input to rebind
- Added an 'invert up/down' that just inverts the 'pitch up' and 'pitch down' buttons (I thought it was useful)
- Persistence between sessions
Capture d’écran 2022-05-08 à 00 15 30
By selecting the right Input Action, you drag the 'selected binding' to select the right input (keyboard, gamepad...)

https://user-images.githubusercontent.com/82713835/167273547-5f2b3543-67bc-4230-8e71-c988ec4f1f7e.mov

Hope this PR is now OK :)

### CODE REVIEW

**Comment by SebLague** [comment]
Great work, thank you! There are a few small issues that need to be addressed before I merge this (if you don't want to work on this any further btw, feel free to leave the pr open and I will make the changes myself later when I have time).

* Font size should match rest of settings menu (30 instead of 36)
* For some reason I am unable to bind the 'E' key to anything.
* For consistency with the rest of the settings menu, rebindings should not be saved if you exit without first pressing 'Apply'.
* If you click to rebind a control, then exit the menu (or change to a different settings tab) without binding a key, you're still able to rebind the control from outside of the menu.

Low priority (not necessary for merge)
* You should not be able to rebind multiple keys at once (clicking on one rebind button while another is active should automatically deactivate the old one).

**Comment by fsioni** [comment]
> Great work, thank you! There are a few small issues that need to be addressed before I merge this (if you don't want to work on this any further btw, feel free to leave the pr open and I will make the changes myself later when I have time).
> 
> * Font size should match rest of settings menu (30 instead of 36)
> * For some reason I am unable to bind the 'E' key to anything.
> * For consistency with the rest of the settings menu, rebindings should not be saved if you exit without first pressing 'Apply'.
> * If you click to rebind a control, then exit the menu (or change to a different settings tab) without binding a key, you're still able to rebind the control from outside of the menu.
> 
> Low priority (not necessary for merge)
> * You should not be able to rebind multiple keys at once (clicking on one rebind button while another is active should automatically deactivate the old one).
> 
> 

Thanks 🙂
Glad that it almost suits the project ! 
I will definitely improve the system with your advice and few other things !
I will work on this 👌

**Comment by fsioni** [comment]
Hello Sebastian !

- I fixed the font size on the controls settings menu
- The E key problem is 'fixed'. It's now working, but I don't know why I needed to do what I did to solve this :/
- Now, the settings are saved by pressing 'Apply', and they are cancelled by quitting the menu, either by exiting via the button or closing the app
- The action 'Rebinding' is now cancelled when changing settings panel/quitting the settings menu
- It is now impossible to assign two keys at the same time
- I added some controls that weren't on the last version on the controls panel : Boost, speed controls, drop package...
- I modified the scroll sensitivity on the controls panel, it was too low

https://user-images.githubusercontent.com/82713835/167317450-3bc3d680-0273-43f9-a370-571272f8c404.mov

**Comment by SebLague** [comment]
Fantastic work, thank you!

**Pull request merged**
